/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mvbos.ame;

import java.util.List;

/**
 *
 * @author Marcus Becker
 */
public class CodeWindow extends javax.swing.JFrame {

    public CodeWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();

        text.setColumns(20);
        text.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables

    StringBuilder sb = new StringBuilder();

    public void setList(List<char[][]> list) {
        sb.append("char[][][] arr = {\n");

        for (int index = 0; index < list.size(); index++) {
            char[][] arr = list.get(index);

            sb.append("{\n");

            for (int col = 0; col < arr.length; col++) {

                sb.append("\t{");

                for (int lin = 0; lin < arr[col].length; lin++) {
                    char val = arr[lin][col];

                    if (val == 0) {
                        val = ' ';
                    }

                    sb.append("'").append(val).append("'");

                    if (lin < arr[col].length - 1) {
                        sb.append(", ");
                    } else {
                        sb.append(" ");
                    }
                }

                if (col < arr.length - 1) {
                    sb.append("},\n");
                } else {
                    sb.append("}\n");
                }
            }

            if (index < list.size() - 1) {
                sb.append("},\n");
            } else {
                sb.append("}");
            }
        }

        sb.append("};");

        text.setText(sb.toString());
    }

    private void monta() {

    }
}
